### ISSUE TITLE
Local dictionaries

### ISSUE THREAD

**Issue by bittlingmayer** [luismond/tm2tb#3]
For this who cannot send data to a 3rd party API for data confidentiality reasons, it would be cool to use local dictionaries, like Hunspell (which is complete enough to power OS/browser spellchecking).

**Comment by luismond** [comment]
Now the module works offline via language models. The MT API concordance has been removed.

**Comment by luismond** [comment]
@bittlingmayer : now the module works offline via language models. The MT API concordance has been removed.
